#!/bin/sh
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/e/eglibc/libc6_2.19-0ubuntu6.3_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/g/gcc-4.8/libasan0_4.8.2-19ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/g/gcc-4.8/libatomic1_4.8.2-19ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/g/gcc-4.8/libgfortran3_4.8.2-19ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/g/gcc-4.8/libgomp1_4.8.2-19ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/universe/h/hdf5/libhdf5-7_1.8.11-5ubuntu7_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/g/gcc-4.8/libitm1_4.8.2-19ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/t/tcl8.6/libtcl8.6_8.6.1-4ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/t/tk8.6/libtk8.6_8.6.1-3ubuntu2_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/universe/h/hwloc/libhwloc5_1.8-1ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/universe/b/blcr/libcr0_0.8.5-2.1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/universe/m/mpich/libmpich10_3.0.4-6ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils_2.24-5ubuntu3_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/e/eglibc/libc-dev-bin_2.19-0ubuntu6.3_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_3.13.0-35.62_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/e/eglibc/libc6-dev_2.19-0ubuntu6.3_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/g/gcc-4.8/libgcc-4.8-dev_4.8.2-19ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/g/gcc-4.8/gcc-4.8_4.8.2-19ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/gcc_4.8.2-1ubuntu6_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/g/gcc-4.8/libstdc++-4.8-dev_4.8.2-19ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/g/gcc-4.8/g++-4.8_4.8.2-19ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/g++_4.8.2-1ubuntu6_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/m/make-dfsg/make_3.81-8.2ubuntu3_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/d/dpkg/libdpkg-perl_1.17.5ubuntu5.3_all.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/d/dpkg/dpkg-dev_1.17.5ubuntu5.3_all.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/b/build-essential/build-essential_11.6ubuntu6_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/f/fakeroot/libfakeroot_1.20-3ubuntu2_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/f/fakeroot/fakeroot_1.20-3ubuntu2_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/g/gcc-4.8/libgfortran-4.8-dev_4.8.2-19ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/g/gcc-4.8/gfortran-4.8_4.8.2-19ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/gfortran_4.8.2-1ubuntu6_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/liba/libalgorithm-diff-perl/libalgorithm-diff-perl_1.19.02-3_all.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/liba/libalgorithm-diff-xs-perl/libalgorithm-diff-xs-perl_0.04-2build4_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/liba/libalgorithm-merge-perl/libalgorithm-merge-perl_0.08-2_all.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/b/blas/libblas3_1.2.20110419-7_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/universe/b/blcr/libcr-dev_0.8.5-2.1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/libf/libfile-fcntllock-perl/libfile-fcntllock-perl_0.14-2build1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/l/lapack/liblapack3_3.5.0-2ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/universe/n/netcdf/libnetcdfc7_4.1.3-7ubuntu2_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/m/manpages/manpages-dev_3.54-1ubuntu1_all.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/p/python-numpy/python-numpy_1.8.1-1ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/universe/p/python-scientific/python-scientific_2.9.4-1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/universe/p/python-scientific/python-mpi_2.9.4-1_all.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/universe/p/python-scientific/mpich2python_2.9.4-1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/restricted/n/nvidia-graphics-drivers-331-updates/nvidia-libopencl1-331-updates_331.38-0ubuntu7.1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/universe/p/python-support/python-support_1.0.15_all.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/universe/p/pyro/pyro_3.14-1.1_all.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/universe/p/python-scientific/python-netcdf_2.9.4-1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/main/p/python-stdlib-extensions/python-tk_2.7.5-1ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/universe/h/hwloc/hwloc-nox_1.8-1ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/universe/h/hwloc/libhwloc-plugins_1.8-1ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/universe/m/mpich/libmpich-dev_3.0.4-6ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/universe/m/mpich/mpich_3.0.4-6ubuntu1_i386.deb
wget -c http://ru.archive.ubuntu.com/ubuntu/pool/universe/m/mpich/mpich2_3.0.4-6ubuntu1_i386.deb
